#! /bin/bash

HOST_ARCH=aarch64
HOST_OS_KIND=ubuntu
HOST_OS_VERSION=18.04
TARGET_ARCH=aarch64
TARGET_OS_KIND=ubuntu
TARGET_OS_VERSION=18.04
COMPILER_KIND=gcc
COMPILER_VERSION=8
COMPILER_CXX_DIALECT=14

