#! /bin/bash

HOST_ARCH=ppc64le
HOST_OS_KIND=centos
HOST_OS_VERSION=8.3.2011
TARGET_ARCH=ppc64le
TARGET_OS_KIND=centos
TARGET_OS_VERSION=8.3.2011
COMPILER_KIND=hpc
COMPILER_VERSION=20.9
COMPILER_CXX_DIALECT=14
